[package]
name = "megaton-example"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]

[dependencies]
megaton-hammer = { path = "../megaton-hammer", features = ["crt0"] }
megaton-ipc = { path = "../megaton-ipc" }
